# Generated by Django 3.0.6 on 2020-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
