# Generated by Django 3.0.6 on 2020-06-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_gategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gategory',
            new_name='Category',
        ),
    ]
