# Generated by Django 3.0.6 on 2020-06-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='exeperience',
            new_name='experience',
        ),
    ]
